[package]
name = "pnp-companion-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.7"
serde = {version = "1.0.152", features = ["derive"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.25.0", features = ["full"] }
xmltojson = { git = "https://github.com/rtyler/xmltojson", branch = "main" }
tower-http = {version="0.3.5", features = ["cors"]}
